minetest.register_craftitem('epic:float_crystal', {
   description = 'Actinolite Crystal',
   inventory_image = 'epic_actinolite_crystal.png'
})

minetest.register_craftitem('epic:float_crystal_shard', {
   description = 'Actinolite Crystal Shard',
   inventory_image = 'epic_actinolite_crystal_shard.png',
   stack_max = 891,
})

minetest.register_craftitem('epic:bloodstone', {
   description = 'Bloodstone',
   inventory_image = 'epic_bloodstone.png'
})

minetest.register_craftitem('epic:thennium', {
   description = 'Rose Thennium',
   inventory_image = 'epic_thennium.png'
})

minetest.register_craftitem('epic:bloodstone_shard', {
   description = 'Bloodstone Shard',
   inventory_image = 'epic_bloodstone_shard.png',
   stack_max = 891,
})

minetest.register_craftitem('epic:bloodstone_powder', {
   description = 'Bloodstone Powder',
   inventory_image = 'epic_bloodstone_powder.png',
   stack_max = 999,
})

minetest.register_craftitem('epic:teleport_powder', {
   description = 'Teleport powder',
   inventory_image = 'epic_teleport_powder.png',
})

minetest.register_craftitem('epic:ash', {
   description = 'Wood ash',
   inventory_image = 'epic_ash.png',
})

minetest.register_craftitem('epic:healing_powder', {
   description = 'Healing powder',
   inventory_image = 'epic_healing_powder.png',
   on_use = function(itemstack, user, pointed_thing)
      local hp = user:get_hp()
      user:set_hp(hp+20)
      local pos = user:get_pos()
      particles_healing(pos)
      local objs = minetest.get_objects_inside_radius(pos, 4)
      for _, obj in pairs(objs) do
         if obj:is_player() then
            local hp = obj:get_hp()
            local x = hp + hp/4
            obj:set_hp(x)
         end
      end
      itemstack:take_item(1); return itemstack
   end
})

minetest.register_craftitem('epic:salt_lump', {
	description = 'Salt lump',
	inventory_image = 'epic_salt_lump.png'
})

minetest.register_craftitem('epic:salt', {
	description = 'Salt',
	inventory_image = 'epic_salt.png'
})

minetest.register_craftitem('epic:potassium_nitrate', {
	description = 'Potassium Nitrate',
	inventory_image = 'epic_potassium_nitrate.png'
})

minetest.register_craftitem('epic:sulfur_lump', {
   description = 'Sulfur lump',
   inventory_image = 'epic_sulfur_lump.png'
})

minetest.register_craftitem('epic:sulfur_dust', {
   description = 'Sulfur dust',
   inventory_image = 'epic_sulfur_dust.png'
})

minetest.register_craftitem('epic:garnet', {
   description = 'Garnet',
   inventory_image = 'epic_garnet.png'
})

minetest.register_craftitem('epic:arrow_tip', {
   description = 'Arrow tip',
   inventory_image = 'epic_arrow_tip.png'
})

minetest.register_craftitem('epic:titanium_lump', {
   description = 'Titanium lump',
   inventory_image = 'epic_titanium_lump.png'
})

minetest.register_craftitem('epic:titanium_ingot', {
   description = 'Titanium ingot',
   inventory_image = 'epic_titanium_ingot.png'
})

minetest.register_craftitem('epic:deed', {
   description = 'Land deed',
   inventory_image = 'epic_deed.png'
})

minetest.register_craftitem('epic:huntite', {
   description = 'Huntite',
   inventory_image = 'epic_huntite.png'
})

minetest.register_craftitem('epic:lead_lump', {
   description = 'Lead lump',
   inventory_image = 'epic_lead_lump.png',
})

minetest.register_craftitem('epic:lead_wire', {
   description = 'Lead wire',
   inventory_image = 'epic_lead_wire.png',
})

minetest.register_craftitem('epic:laputa', {
   description = 'Laputa',
   inventory_image = 'epic_laputa_inv.png',
   groups = {not_in_creative_inventory=1},
   on_use = function(itemstack, user, pointed_thing)
     local pos = user:get_pos()
     local lower_pos = {x=pos.x, y=pos.y-3, z=pos.z}
     minetest.set_node(lower_pos, {name = 'epic:floating_base'})
     itemstack:take_item(1);
     return itemstack
  end,
})

minetest.register_craftitem('epic:glowstone_fragment', {
   description = 'Glowstone Fragment',
   inventory_image = 'epic_glowstone_fragment.png',
})

minetest.register_craftitem('epic:glowingdiamond', {
   description = 'Glowing Diamond',
   inventory_image = 'epic_glowingdiamond.png',
})

minetest.register_craftitem('epic:burlap_tattered', {
   description = 'Tattered Burlap',
   inventory_image = 'epic_burlap_tattered.png',
})

minetest.register_craftitem('epic:burlap', {
   description = 'Burlap',
   inventory_image = 'epic_burlap.png'
})
