local function register_basic(name, desc) --Registers node, stairs, slabs. With same texture on all sides.
   minetest.register_node('furniture:'..name, {
      description = desc,
      tiles = {{name='furniture_'..name..'.png', align_style='world', scale=4}},
      inventory_image = '[inventorycube{furniture_'..name..'.png&[sheet:4x4:1,1{furniture_'..name..'.png&[sheet:4x4:1,1{furniture_'..name..'.png&[sheet:4x4:1,1',
      groups = {choppy = 2, oddly_breakable_by_hand = 2, flammable = 2, wood = 1},
   	sounds = default.node_sound_wood_defaults(),
   })

   stairs.register_stair_and_slab(
      name,
      'furniture:'..name,
      {choppy = 2, oddly_breakable_by_hand = 2, flammable = 2, wood = 1},
      {{name='furniture_'..name..'.png', align_style='world', scale=4}},
      desc..' Stair',
      desc..' Slab',
      default.node_sound_wood_defaults(),
      true)
end

register_basic('wood_1', 'Wood Floor (Style 1)')
register_basic('wood_2', 'Wood Floor (Style 2)')
register_basic('wood_3', 'Wood Floor (Style 3)')
register_basic('wood_4', 'Wood Floor (Style 4)')

minetest.register_craft({
   output = 'furniture:wood_1 2',
   recipe = {
      {'default:wood', 'default:junglewood'}
   }
})

minetest.register_craft({
   output = 'furniture:wood_2 2',
   recipe = {
      {'default:junglewood', 'default:wood'}
   }
})

minetest.register_craft({
   output = 'furniture:wood_3 2',
   recipe = {
      {'default:wood'},
      {'default:junglewood'}
   }
})

minetest.register_craft({
   output = 'furniture:wood_4 2',
   recipe = {
      {'default:junglewood'},
      {'default:wood'}
   }
})
